# Generated by Django 5.2.4 on 2025-07-08 15:35

import django.db.models.deletion
import ocr_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OCRJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload an image containing text",
                        upload_to=ocr_app.models.image_upload_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed at"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error message"
                    ),
                ),
                (
                    "word_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=ocr_app.models.document_upload_path,
                        verbose_name="Word document",
                    ),
                ),
            ],
            options={
                "verbose_name": "OCR Job",
                "verbose_name_plural": "OCR Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OCRResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Text content")),
                (
                    "confidence",
                    models.FloatField(
                        help_text="OCR confidence score (0-1)",
                        verbose_name="Confidence score",
                    ),
                ),
                ("x1", models.IntegerField(verbose_name="X1")),
                ("y1", models.IntegerField(verbose_name="Y1")),
                ("x2", models.IntegerField(verbose_name="X2")),
                ("y2", models.IntegerField(verbose_name="Y2")),
                ("x3", models.IntegerField(verbose_name="X3")),
                ("y3", models.IntegerField(verbose_name="Y3")),
                ("x4", models.IntegerField(verbose_name="X4")),
                ("y4", models.IntegerField(verbose_name="Y4")),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="ocr_app.ocrjob",
                        verbose_name="OCR Job",
                    ),
                ),
            ],
            options={
                "verbose_name": "OCR Result",
                "verbose_name_plural": "OCR Results",
                "ordering": ["y1"],
            },
        ),
    ]
