# Generated by Django 5.2.4 on 2025-07-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrjob",
            name="last_retry_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last retry at"
            ),
        ),
        migrations.AddField(
            model_name="ocrjob",
            name="retry_count",
            field=models.IntegerField(
                default=0,
                help_text="Number of times this job has been retried",
                verbose_name="Retry count",
            ),
        ),
    ]
