# Generated by Django 5.2.4 on 2025-07-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr_app", "0002_ocrjob_last_retry_at_ocrjob_retry_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrjob",
            name="average_confidence",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Average confidence score"
            ),
        ),
        migrations.AddField(
            model_name="ocrjob",
            name="image_height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ocrjob",
            name="image_width",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ocrjob",
            name="preprocessed",
            field=models.BooleanField(
                default=False, verbose_name="Image was preprocessed"
            ),
        ),
        migrations.AddField(
            model_name="ocrjob",
            name="processing_time",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Processing time (seconds)"
            ),
        ),
        migrations.AddField(
            model_name="ocrjob",
            name="total_text_items",
            field=models.IntegerField(default=0, verbose_name="Total text items found"),
        ),
    ]
